### ISSUE TITLE
issue with type casting

### ISSUE THREAD

**Issue by codeperfectplus** [ambushneupane/InstaBot#1]
```bash
File "/home/codeperfectplus/Documents/PrivateTestCode/Automation/InstaBot/instascript.py", line 51, in following
    self.numoffollowing = int(values)                                                                             
ValueError: invalid literal for int() with base 10: '1,700'
```

**Comment by ambushneupane** [comment]
Well I made this code that works only for me cause I don't have much
following or followers (I have both less than 1k so, did not thought of it
).Since you also want to test it, I must make it for all ! I will soon fix
it and mail you. By the way,Thanks for Informing about the error !!

**Comment by ambushneupane** [comment]
I think I solved the error ! Let me know if you had any problem while
running the code. https://github.com/ambushneupane/InstaBot

**Comment by ambushneupane** [comment]
Check it! may be this time it will work

**Comment by codeperfectplus** [comment]
Now the error is solved but it's scrolling the list not unfollowing anyone. maybe something is broken.

**Comment by ambushneupane** [comment]
Well It's not that advanced to unfollow while scrolling down the list. What it does is it scrolls the followers and following list and grabs the link of the account which has not follwed us.It then goes to the url of those accounts and then unfollows the account.But it won't unfollow some bigger personalities accounts (based on their followers,I am assuming that they have more than 1000 followers but you can assume your own ).If you are getting any kind of error while running the code Inform me.I will try my best to fix it out!!!

**Comment by codeperfectplus** [comment]
Thanks, for fixing the problem. I am just learning selenium.
