### ISSUE TITLE
Will I be ratelimited by Instagram?

### ISSUE THREAD

**Issue by tripulse** [ambushneupane/InstaBot#2]
There's no such information about rate-limitation by Instagram in the documentation of this project. The owner must provide an explanation on this, as this question is quite brutal.

**Comment by ambushneupane** [comment]
I haven't experienced any limits so far. So I couldn't say anything about it.

**Comment by tripulse** [comment]
Ok, so I should only proceed with an account which is secondary to me (because there's no surety).
